# Generated by Django 5.1 on 2024-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=255)),
                ('video_width', models.IntegerField()),
                ('video_height', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('fontsize', models.FloatField()),
                ('color', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
